name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Install unzip
      run: sudo apt-get install unzip -y

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install Xfce and xrdp
      run: |
        sudo apt-get update
        sudo apt-get install xfce4 xfce4-goodies xrdp -y
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set xfce4 as default session
      run: echo xfce4-session >~/.xsession

    - name: Set password for runner user
      run: echo 'runner:$PASSWORD' | sudo chpasswd
      env:
        PASSWORD: ${{ secrets.RUNNER_PASSWORD }}

    - name: Create ngrok tunnel
      run: ./ngrok tcp 3389
